/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package xp.ui;

import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.time.LocalDate;
import java.util.ArrayList;

import com.lowagie.text.Document;
import com.lowagie.text.DocumentException;
import com.lowagie.text.Element;
import com.lowagie.text.Font;
import com.lowagie.text.FontFactory;
import com.lowagie.text.Image;
import com.lowagie.text.Paragraph;
import com.lowagie.text.pdf.PdfWriter;

import xp.db.T_cliente;
import xp.db.T_inmueble;
import xp.model.Reserva;
import xp.model.Venta;

/**
 *
 * @author Lucia
 */
public class GenerarVenta extends javax.swing.JPanel {
	
public static final String LOGO="C:\\Users\\Lucia\\git\\TP_MetAgi_2021\\logo.jpeg";
    
    
    public static void crearPDF(Venta reserva) throws DocumentException, IOException, Exception {
		Document documento = new Document();
		
		
		FileOutputStream fichero = new FileOutputStream("comprobante.pdf");
		PdfWriter.getInstance(documento, fichero);
		
		documento.open();
		
		Image img = Image.getInstance(LOGO);
		img.setAlignment(img.ALIGN_CENTER);
		 documento.add(img);
		
		Paragraph titulo = new Paragraph("Comprobante de Venta \n \n ",
				FontFactory.getFont("arial",22,
				Font.BOLD));
		titulo.setAlignment(titulo.ALIGN_CENTER);
		documento.add(titulo);
		documento.add(new Paragraph("Id inmueble: " + reserva.getIdI()));
    	documento.add(new Paragraph("Barrio: " + reserva.getBarrioI()));
    	documento.add(new Paragraph("Cliente DNI: " + reserva.getDniC()));
    	documento.add(new Paragraph("Precio de venta: " + reserva.getMonto()));
    	documento.add(new Paragraph("Nuevo dueño: " + reserva.getNombreC() ));
    	
    	Paragraph fecha = new Paragraph("\n \n \n \n \n Se deja constancia que al dia de la fecha "+ reserva.getFecha()+ "se vendio el inmueble "+ reserva.getCodigoI() );
    	documento.add(fecha);
    	
		
		
		
		
		documento.close();
				
	}

    /**
     * Creates new form GenerarVenta
     * @param barrioSelected 
     * @param provinciaSelected 
     * @param localidadSelected 
     * @param codigoSelected 
     * @param idSelected 
     */
    public GenerarVenta(Object idSelected, String codigoSelected, String localidadSelected, String provinciaSelected, String barrioSelected) {
        initComponents(idSelected,codigoSelected,localidadSelected,provinciaSelected,barrioSelected);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * @param barrioSelected 
     * @param provinciaSelected 
     * @param localidadSelected 
     * @param codigoSelected 
     * @param idSelected 
     * @param barrioSelected 
     * @param provinciaSelected 
     * @param localidadSelected 
     * @param codigoSelected 
     * @param idSelected 
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents(Object idSelected, String codigoSelected, String localidadSelected, String provinciaSelected, String barrioSelected) {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jventa = new javax.swing.JLabel();
        jInmueble = new javax.swing.JLabel();
        jComboBoxInmueble = new javax.swing.JComboBox<>();
        nombreC = new javax.swing.JLabel();
        jnombreC = new javax.swing.JTextField();
        japellido = new javax.swing.JLabel();
        japellidoC = new javax.swing.JTextField();
        jmontoC = new javax.swing.JLabel();
        jmonto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jobservaciones = new javax.swing.JTextField();
        btnVenta = new javax.swing.JButton();
        dnic = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        jTextField1.setText("jTextField1");

        jventa.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jventa.setText("Nueva Venta");

        jInmueble.setText("Inmueble");

        jComboBoxInmueble.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        nombreC.setText("Nombre Cliente");

        japellido.setText("Apellido Cliente");

        jmontoC.setText("Monto depositado");

        jmonto.setText("$$$$$$$$");

        jLabel1.setText("Observaciones");

        btnVenta.setText("Generar comprobante");

        dnic.setText("DNI Cliente");

        T_inmueble Ti2 = new T_inmueble();
		ArrayList<String> i2_rs = new ArrayList<String>();
	    i2_rs= Ti2.buscar_codigo();
	    for (String nom: i2_rs) {
	    	jComboBoxInmueble.addItem(nom);
	    	}
	    jComboBoxInmueble.setSelectedItem(codigoSelected);
	    
	    T_cliente Ti3 = new T_cliente();
		ArrayList<String> i3_rs = new ArrayList<String>();
	    i3_rs= Ti3.buscar_c();
	    for (String nom: i3_rs) {
	    	jComboBox1.addItem(nom);}
	    jComboBox1.setSelectedItem(null);
	    
	    btnVenta.addActionListener(e -> {
        	String precio;
            String cliente;
            String apellidoc;
            String nombrec;
            
        	cliente=(String)jComboBox1.getSelectedItem(); 
            precio=jmonto.getText(); 
            nombrec=jnombreC.getText();
            apellidoc=japellidoC.getText();
            
            
            Venta reserva = new Venta();
            reserva.setDniC(cliente);
            reserva.setApellidoC(apellidoc);
            reserva.setNombreC(nombrec);
            reserva.setMonto(precio);
            reserva.setBarrioI(barrioSelected);
            reserva.setCodigoI(codigoSelected);
            reserva.setIdI((String)idSelected);
            reserva.setFecha(LocalDate.now());
            
            
            
            this.dispose(); //aca me marca error
          
            
        	try {
				crearPDF(reserva);
			} catch (FileNotFoundException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			} catch (DocumentException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			} catch (IOException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			} catch (Exception e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
        	
        	T_inmueble tinmueble = new T_inmueble();
			tinmueble.updateV(idSelected);
        	
        });
        
        
        

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 144, Short.MAX_VALUE)
                .addComponent(btnVenta)
                .addGap(137, 137, 137))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(156, 156, 156)
                            .addComponent(jventa))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(37, 37, 37)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboBoxInmueble, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jInmueble, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nombreC, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jnombreC, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jmontoC, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jmonto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                                    .addGap(37, 37, 37)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(japellido)
                                        .addComponent(japellidoC)
                                        .addComponent(jLabel1)
                                        .addComponent(jobservaciones, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                                        .addComponent(dnic)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jventa)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jInmueble)
                    .addComponent(dnic))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxInmueble, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreC)
                    .addComponent(japellido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jnombreC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(japellidoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jmontoC)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jmonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jobservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(btnVenta)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVenta;
    private javax.swing.JLabel dnic;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBoxInmueble;
    private javax.swing.JLabel jInmueble;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel japellido;
    private javax.swing.JTextField japellidoC;
    private javax.swing.JTextField jmonto;
    private javax.swing.JLabel jmontoC;
    private javax.swing.JTextField jnombreC;
    private javax.swing.JTextField jobservaciones;
    private javax.swing.JLabel jventa;
    private javax.swing.JLabel nombreC;
    // End of variables declaration//GEN-END:variables
}
